import type { Metadata } from 'next'
import localFont from 'next/font/local'
import Head from 'next/head'
import { AOSInit } from './aos'
import './globals.css'
import "aos/dist/aos.css";
import { useEffect } from 'react';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}



export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <>
      <html lang="en">
        <AOSInit />
        <body className="font-['Proxima Nova']">
          {children}
        </body>
      </html>
    </>
   
  )
}
